### ISSUE TITLE
EXSRV003 - Check version of the .NET Framework

### ISSUE THREAD

**Issue by mnivens** [ExchangeAnalyzer/ExchangeAnalyzer#113]
Checks the version of the .NET framework to verify it is at the recommended version (4.5.2).

**Comment by mnivens** [comment]
Checked changes into branch EXSRV003 and submitted pull request.

**Comment by cunninghamp** [comment]
In https://github.com/ExchangeAnalyzer/ExchangeAnalyzer/releases/tag/v0.2.1-beta.5
