### ISSUE TITLE
Error in running script

### ISSUE THREAD

**Issue by Toddlemm** [ExchangeAnalyzer/ExchangeAnalyzer#118]
At C:\scripts\exchangeanalyzer\Run-ExchangeAnalyzer.ps1:446 char:5
-     $ServerADSite = ($ExchangeServers | Where {$_.Name -ieq $($server.Name)}).Si ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : InvokeMethodOnNull

VERBOSE: Finished

**Comment by cunninghamp** [comment]
Please describe your Exchange environment, and how you are running the script.

**Comment by swngdnz** [comment]
Isn't this the same as the 2013 vs. 2016 bug before? Format of the return object had changed?

**Comment by cunninghamp** [comment]
@swngdnz yes, I'm surprised to see the bug report, since neither Exchange 2013 or 2016 show the issue in my lab with the latest release of the script.

**Comment by Toddlemm** [comment]
Two CAS/MB virtual servers running Exchange 2013 CU9. Running the script
from Powershell on one of the Exchange 2013 servers, in the
ExchangeAnalyzer folder.

On Thu, Mar 31, 2016 at 5:31 PM, Paul Cunningham <notifications@github.com>
wrote:

> Please describe your Exchange environment, and how you are running the
> script.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cunninghamp/ExchangeAnalyzer/issues/118#issuecomment-204157228>
>



-- 
T. Todd Lemmiksoo

**Comment by Toddlemm** [comment]
*** Change Log ***

v0.2.0-Beta.4, 31/3/2016 - Fourth public beta release
v0.1.2-Beta.3, 18/02/2016 - Third public beta release
v0.1.1-Beta.2, 28/01/2016 - Second public beta release
v0.1.0-Beta.1, 14/01/2016 - Public beta release


On Thu, Mar 31, 2016 at 10:28 PM, Paul Cunningham <notifications@github.com>
wrote:

> Still can't repro, unless it's a CU9 thing.
>
> @Toddlemm <https://github.com/Toddlemm> can you please confirm you are
> running the latest release of the script?
>
> https://github.com/cunninghamp/ExchangeAnalyzer/releases
>
> Or just open the script in your editor and look at the change log.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cunninghamp/ExchangeAnalyzer/issues/118#issuecomment-204229785>
>



-- 
T. Todd Lemmiksoo

**Comment by cunninghamp** [comment]
Was unable to repro this.
