### ISSUE TITLE
Request: Missing hotfixes

### ISSUE THREAD

**Issue by cunninghamp** [ExchangeAnalyzer/ExchangeAnalyzer#121]
User comment:

Would be nice if the tool would be able to find missing special hotfixes (which didn´t come directly via windows updates) as some needs to be downloaded manually, but you need to read true all the KBs to find a possible one which is quite time consuming ... So getting a list of possible updates which can be applied manually would be very helpfull as then only these KBs needs to be checked.

**Comment by swngdnz** [comment]
This is a huge can of worms if you look at all of the infrastructure that Exchange uses. Windows Server vs. Failover Clustering vs. Exchange vs. VSS vs. .NET vs. etc. I maintained a list for almost a year on WFC for Server 2008 R2 and Server 2012, Maintaining it was several hours per month.

If you limit it exclusively to Exchange - then it's doable.

**Comment by swngdnz** [comment]
I used get-hotfix. I've attached the XML files and PowerShell script I used. The time I spent monthly was in tracking down the updates, determining what superseded what, and updating the XML files.

[HyperV-and-Cluster-Updates.zip](https://github.com/cunninghamp/ExchangeAnalyzer/files/200394/HyperV-and-Cluster-Updates.zip)
