### ISSUE TITLE
Script Doesn't Assert that it is in an EMS Window

### ISSUE THREAD

**Issue by bdesmond** [ExchangeAnalyzer/ExchangeAnalyzer#122]
We shouldn't let the user un the script and then have it fail when it can't find the Exchange cmdlets. This should be a hard block at the start.

**Comment by swngdnz** [comment]
OK. Should it attempt to load them? Or simply require to be in EMS?

If it attempts to load them, should it respect RBAC? Or do it the easy way?

**Comment by bdesmond** [comment]
I think the cheap fix for now is to bail if you’re not in an EMS window.

Asserting that you have the right cmdlets (we’d need to track them) would be nice but unnecessary at this juncture.

**Comment by swngdnz** [comment]
Simple choice is

               if( -not ( Get-Command Get-ExchangeServer ) )
               {
                              throw “Must be executed from an Exchange Management Shell”
               }
