### ISSUE TITLE
HW001 InvalidOperation error

### ISSUE THREAD

**Issue by cunninghamp** [ExchangeAnalyzer/ExchangeAnalyzer#154]
Reported via [TechNet](https://gallery.technet.microsoft.com/Exchange-Analyzer-6e20132e/view/Discussions)

> I am running the latest version of the script however i keep receiving the following error:
> 
> Get-WmiObject :
> At D:\Software\ExchangeAnalyzer-0.2.0-beta.4c\ExchangeAnalyzer-0.2.0-beta.4c\Tests\HW001.ps1:23 char:20
> -         $virtual = Get-WmiObject -ComputerName $name -Class Win32_ComputerSystem
> -                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : InvalidOperation: (:) [Get-WmiObject], COMException
>   - FullyQualifiedErrorId : GetWMICOMException,Microsoft.PowerShell.Commands.GetWmiObjectCommand

**Comment by damianscoles** [comment]
I have updated code for this scenario.  It will query CIM and then WMI for this information.

**Comment by cunninghamp** [comment]
For future patches best to create a branch for the fix, commit your change to the branch and do a PR for review instead of committing directly to development branch.

If this is testing okay then the issue can be closed.
