### ISSUE TITLE
TEST/XCAS/Namespace/TTL on DNS entries

### ISSUE THREAD

**Issue by cunninghamp** [ExchangeAnalyzer/ExchangeAnalyzer#155]
Test to check the TTL on DNS entries for CAS namespaces and flag if they are higher than recommended practice.

Suggestions:
- check internal and external names against default DNS servers
- check external names against 8.8.8.8 or a public DNS server as well, for split DNS scenarios. Will need to error handle this for servers that can't reach public DNS servers.
- for internal names, TTL of up to 5 minutes is okay, higher than 5 minutes I suggest a warning, higher than 1 hour I suggest a fail unless environment has only a single Exchange 2013 CAS or 2016 MBX

@chrisbrownie will take this one.

**Comment by chrisbrownie** [comment]
@cunninghamp, do you have any thoughts around acceptable TTLs for external records? Obviously that's difficult to come to a reasonable decision on, given that there's a very high likelihood that external CAS is via some sort of load balancing appliance or system, thus rendering TTLs somewhat irrelevant.

**Comment by cunninghamp** [comment]
Anyone who is doing it smartly, e.g load balancing or Route 53 health checks, would want a low TTL. Anyone who is doing it the hard way, e.g. manual switchover, would also need a low TTL.

If your test logic can determine that Exchange servers with external URLs exist in more than one AD site, that might be a sign that some form of external failover is in place and a low TTL should be used.

**Comment by cunninghamp** [comment]
In https://github.com/ExchangeAnalyzer/ExchangeAnalyzer/releases/tag/v0.2.1-beta.5
