### ISSUE TITLE
Documentation for CAS005

### ISSUE THREAD

**Issue by cunninghamp** [ExchangeAnalyzer/ExchangeAnalyzer#162]
PR #161 for test CAS005 has been merged to the development branch.

Please write a documentation page for CAS005 in the Wiki.
https://github.com/ExchangeAnalyzer/ExchangeAnalyzer/wiki/CAS005

A template is available here:
https://github.com/ExchangeAnalyzer/ExchangeAnalyzer/wiki/TESTID

Please update the Exchange Analyzer tests page with your test details.
https://github.com/ExchangeAnalyzer/ExchangeAnalyzer/wiki/Exchange-Analyzer-Tests

Close this issue when the documentation page has been written.

If this is the first contribution you can also update the Contributors page in the Wiki with your details.
https://github.com/ExchangeAnalyzer/ExchangeAnalyzer/wiki/Contributors

**Comment by cunninghamp** [comment]
@chrisbrownie

**Comment by chrisbrownie** [comment]
Done

**Comment by cunninghamp** [comment]
Some suggested edits made.
