### ISSUE TITLE
TEST/EX Exchange Scaning Engine Status 

### ISSUE THREAD

**Issue by blacks7** [ExchangeAnalyzer/ExchangeAnalyzer#170]
Check last successfully Update of Exchange Scaning Engine Status if Scaning Engine is enabled. If Update older than 48 hours, then post Error.

CmdLeds
Add-PSSnapin Microsoft.Exchange.Management.PowerShell.SnapIn
Add-PSSnapin Microsoft.Forefront.Filtering.Management.Powershell
Get-EngineUpdateInformation

Also test correct permissions on Engine Updates Folder:
..\Microsoft Exchange Server 2013\FIP-FS\Data\Engines\amd64\Microsoft\bin

if u install Exchange on other than default path, the permissions on this Folder are not correct.
User NETWORK SERVICE must have Full Access

**Comment by cunninghamp** [comment]
The dependency on Microsoft.Forefront.Filtering.Management.Powershell snapin makes me think this will be difficult or even impossible to implement for the usage scenarios we develop for (e.g. running Exchange Analyzer in a remoting session to an Exchange server).

**Comment by cunninghamp** [comment]
Closing this issue.
