### ISSUE TITLE
INIT/Exchange pssnapin can load automatically

### ISSUE THREAD

**Issue by blacks7** [ExchangeAnalyzer/ExchangeAnalyzer#171]
If starting Script direct in powershell without loading Exchange AddIns, it will get in require error.

u can fix it, by importing Exchange Addins, when they are not loaded. Check if they are allready installed on Server, which execute the script.

add-pssnapin Microsoft.Exchange.Management.PowerShell.SnapIn

**Comment by cunninghamp** [comment]
What error are you receiving? When I open PowerShell, remote to an Exchange server, and run the script it works just fine. If you're getting an error we should look into it.

The other option is to run using the Exchange management shell.

Using Add-PSSnapin is not recommended by Microsoft except under specific support guidance, so I don't think we'll be adding that to the script.

**Comment by blacks7** [comment]
Who said this?

U can list all registered snapins by Get-PSSnapin -Registered and check it, before u integrade it in your code by Add-PSSnapin... so u can catch the error.

For Example: When i want to execute your script by daily / weekly task, I don't want to insert the hole PSSnapin extend by -PSConsoleFile in my Task scheduler...

Think about

**Comment by cunninghamp** [comment]
Here's some info:

https://blogs.technet.microsoft.com/rmilne/2015/01/28/directly-loading-exchange-2010-or-2013-snapin-is-not-supported/

We'd be taking an unsupported approach just to make your scheduled task more convenient to define.

**Comment by swngdnz** [comment]
I agree with Paul. Loading the Exchange environment involves more than just loading the snapin. It also loads the various Exchange types into ETS and formatting information for the various output cmdlets. We develop assuming all of that is in place.

**Comment by chrisbrownie** [comment]
Yeah I'm with @cunninghamp on this too. Suggest closing.

**Comment by cunninghamp** [comment]
Closing this one, as we agree not to take an unsupported approach.
