### ISSUE TITLE
CAS DNS tests failed

### ISSUE THREAD

**Issue by cunninghamp** [ExchangeAnalyzer/ExchangeAnalyzer#180]
Reported by Mike Payne:

Comment: My tests for DNS were failing on ExchangeAnalyzer 0.2.2-beta6. Looking over the Tests (CAS005.ps1), I saw the call to Resolve-DnsName wasn't working. I added #requires -Modules DnsClient to Run-ExchangeAnalyzer.ps1 and this appears to have resolved the issue. Is this the recommended resolution to this issue?

cc @chrisbrownie

**Comment by chrisbrownie** [comment]
@cunninghamp are you happy for me to introduce the DnsClient requiement into the main script? I see ExchangeAnalyzer and ActiveDirectory modules are already present.

https://github.com/ExchangeAnalyzer/ExchangeAnalyzer/blob/4270bb3153bda854f14497c932762868dfd180f5/Run-ExchangeAnalyzer.ps1#L100-L101

**Comment by cunninghamp** [comment]
I guess that implies the entire script will halt if the module doesn't exist. It should exist, even if it's only for one test... so I think it's appropriate to add it there.
