### ISSUE TITLE
Get-OrganizationConfig error when running

### ISSUE THREAD

**Issue by arosenau** [ExchangeAnalyzer/ExchangeAnalyzer#193]
I get the below error when trying to run the tool. I did copy the ExchangeAnalyser module into the WindowsPowerShell\v1.0\Modules directory. This is with an Exchange 2016 server and I"m trying to turn the tool directly on the server.

PS C:\ExchangeAnalyzer-0.2.4-beta.8> .\Run-ExchangeAnalyzer.ps1
WARNING: An error has occurred during basic data collection.
WARNING: The term 'Get-OrganizationConfig' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by cunninghamp** [comment]
Are you running the script from the Exchange Management Shell?

**Comment by arosenau** [comment]
Sometimes its the simplest things you overlook. Thank you. I was running it from standard powershell not the EMS. Running it in EMS works great. Thank you, this is a very useful tool.
