### ISSUE TITLE
ExchangeAnalyzer error during basic collection - screen grab attached

### ISSUE THREAD

**Issue by troedl** [ExchangeAnalyzer/ExchangeAnalyzer#209]
We are running Exchange 2016 on a virtual server running Server 2012 R2.    We downloaded ExchangeAnalyzer and ran it and got the reports and started acting on those.  So far, so good.  One of the errors, was that we were not running the latest build of Exchange.  Sure enough, after checking we identified that our version was a couple of builds old.  So we downloaded the latest Exchange 2016 build and upgraded our server to that version.  

We then tried to run ExchangeAnalyzer from PS and are getting an error:  Warning: An error has occurred during basic data collection.   WARNING: The term "Get-OrganizationConfig" is not recognized as the name of a cmdlet, function, scriptfile, or operable program.   Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

![2017_07_18_exchange_analyzer](https://user-images.githubusercontent.com/30272177/28337047-ed3c602a-6bc9-11e7-9ab0-e8f34dee0bf3.PNG)

Thanks for your assistance

**Comment by swngdnz** [comment]
I suggest you execute the script from an elevated Exchange Management Shell, not regular PowerShell.

Regards,
Michael B.

**Comment by cunninghamp** [comment]
The script must be run from an Exchange Management Shell. That requirement is included in the instructions in the [wiki](https://github.com/ExchangeAnalyzer/ExchangeAnalyzer/wiki/Using-Exchange-Analyzer).

**Comment by troedl** [comment]
Confirmed that running the script from the EMS works fine.   Thanks for the enlightenment, this was indeed in the instructions, my bad.
