### ISSUE TITLE
Exchange 2013 CU23 Released!

### ISSUE THREAD

**Issue by davidenco** [ExchangeAnalyzer/ExchangeAnalyzer#223]
Can you update the provided Exchange Build Numbers please?

https://www.microsoft.com/en-us/download/details.aspx?id=58392

**Comment by chrisbrownie** [comment]
Not looking likely: https://github.com/ExchangeAnalyzer/ExchangeAnalyzer/commit/604f490559d82cea97fda09e80f5b92554cd3f60

You might get lucky if you submit a PR though.

**Comment by davidenco** [comment]
Ah OK, thanks, I'll build it myself then in VS. Thanks.

**Comment by davidenco** [comment]
No worries, thanks. :)
