### ISSUE TITLE
Write-Warning should not be used for terminating errors

### ISSUE THREAD

**Issue by chrisbrownie** [ExchangeAnalyzer/ExchangeAnalyzer#56]
Where a `write-warning` is followed by `exit`, consider replacing it with `Write-Error` or replacing both lines with `throw`. The warning alerts should be reserved only for non-terminating issues.

**Comment by cunninghamp** [comment]
In https://github.com/ExchangeAnalyzer/ExchangeAnalyzer/releases/tag/v0.2.1-beta.5
